version: 2
jobs:
  build:
    docker:
      - image: terrorjack/vanilla:haskell
    steps:
      - checkout
      - restore_cache:
          key: stack-work-
      - run: stack --no-terminal build --haddock --test --no-run-tests
      - save_cache:
          key: stack-work-
          paths:
            - /root/.stack
            - .stack-work
            - examples/.stack-work
            - .buildinfo
            - examples/.buildinfo
      - run: stack --no-terminal test inline-js-examples:inline-js-examples
